services:
  - type: web
    name: studyhub-student-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    headers:
      - source: "/*"
        headers:
          - key: "Cross-Origin-Opener-Policy"
            value: "same-origin-allow-popups"
          - key: "Cross-Origin-Embedder-Policy"
            value: "unsafe-none"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"